export const GENRES = [
  'literary-fiction', 'science-fiction', 'fantasy', 'mystery-thriller', 'horror',
  'romance', 'historical-fiction', 'manga-comics', 'poetry', 'drama',
  'history', 'biography-memoir', 'philosophy', 'politics', 'economics',
  'science', 'technology', 'psychology', 'religion-spirituality', 'sociology',
  'self-help', 'business', 'travel', 'food-cooking', 'art-design',
  'essays', 'journalism', 'india-south-asia', 'literary-criticism', 'nature-environment',
  'other',
] as const

export type Genre = typeof GENRES[number]

export const GENRE_LABELS: Record<Genre, string> = {
  'literary-fiction':      'Literary Fiction',
  'science-fiction':       'Science Fiction',
  'fantasy':               'Fantasy',
  'mystery-thriller':      'Mystery & Thriller',
  'horror':                'Horror',
  'romance':               'Romance',
  'historical-fiction':    'Historical Fiction',
  'manga-comics':          'Manga & Comics',
  'poetry':                'Poetry',
  'drama':                 'Drama',
  'history':               'History',
  'biography-memoir':      'Biography & Memoir',
  'philosophy':            'Philosophy',
  'politics':              'Politics',
  'economics':             'Economics',
  'science':               'Science',
  'technology':            'Technology',
  'psychology':            'Psychology',
  'religion-spirituality': 'Religion & Spirituality',
  'sociology':             'Sociology',
  'self-help':             'Self-Help',
  'business':              'Business',
  'travel':                'Travel',
  'food-cooking':          'Food & Cooking',
  'art-design':            'Art & Design',
  'essays':                'Essays',
  'journalism':            'Journalism',
  'india-south-asia':      'India & South Asia',
  'literary-criticism':    'Literary Criticism',
  'nature-environment':    'Nature & Environment',
  'other':                 'Other',
}
